const ActionTypes = {
    JOBPOSTDATA: 'JOBPOSTDATA',
    STUDENTCURRENTUSER: "STUDENTCURRENTUSER",
    STUDENTPROFILEDATA: "STUDENTPROFILEDATA",
    COMPANYCURRENTUSER: "COMPANYCURRENTUSER",
    COMPANYUSERS: "COMPANYUSERS",
    COMPANYPROFILEDATA: "COMPANYPROFILEDATA",
    COMPANYCURRENTUSERPROF: "COMPANYCURRENTUSERPROF",
    MYCOMPANYJOBPOSTDATA: "MYCOMPANYJOBPOSTDATA",
    STUDENTDATAFORCOMPANY: "STUDENTDATAFORCOMPANY",
    DELETESTUDENT: "DELETESTUDENT",
    DELETECOMPUSERS: "DELETECOMPUSERS",
    JOBPOSTDATAPUSHKEY: "JOBPOSTDATAPUSHKEY",
    JOBUIDKEYS: "JOBUIDKEYS",
    APPLIEDSTUDENTS: "APPLIEDSTUDENTS",
    ERRORSTUDENTSN: "ERRORSTUDENTSN",
    ERRORSTUDENTSU: "ERRORSTUDENTSU",
    ERRORCOMPANYSU: "ERRORCOMPANYSU",
    ERRORCOMPANYSN: "ERRORCOMPANYSN",
    ERRORADMINSN: 'ERRORADMINSN'
}

export default ActionTypes;
